_target_: drone.models.discrete_action_model.DiscreteActionModel
pretrained: false
action_dim: 4
num_bins: 11
action_low: -0.2
action_high: 0.2
output_space: discrete  # Metadata for loss function selection (not passed to constructor)
v3: false